### PR TITLE
Issue 105 + Memory Leak

### PR DESCRIPTION
**Pull request by jormagar**
This pull request fixes issue 105
[ISSUE 105](https://github.com/AndreaVitale/av.imageview/issues/105)

Adds Hans changes on his Pull request
[PR 101](https://github.com/AndreaVitale/av.imageview/pull/101)

[av.imageview-android-5.0.2.zip](https://github.com/AndreaVitale/av.imageview/files/5623038/av.imageview-android-5.0.2.zip)

### CODE REVIEW

**Comment by AndreaVitale** [comment]
Hi guys! Thanks for your work! I'll going to test it right now!

**Comment by hansemannn** [comment]
@prashantsaini1 had some issues with this, since it may cause larger issues. He will comment on it early tomorrow :-)

**Comment by AndreaVitale** [comment]
@hansemannn sorry.. he had issue on what? On your PR code?

**Comment by hansemannn** [comment]
Sorry! With the change in this PR. Quote from our chat:
> Setting that null might even create worse scenarios as activity will need to be set null by proxy itself as per it's class design

**Comment by prashantsaini1** [comment]
Added a new PR here: https://github.com/AndreaVitale/av.imageview/pull/108

**Comment by hansemannn** [comment]
@AndreaVitale 3 PR's to choose from 😄:
- #106 
- #107
- #108 (includes the fix from #107 / @garymathews)

**Pull request merged**
