### PR TITLE
feat: update to Glide 4.9.0

### PR DESCRIPTION
**Pull request by hansemannn**
Opened from `issue-63` by @AndreaVitale so the commits can be tracked here.

### CODE REVIEW

**Comment by hansemannn** [comment]
@andreavitale Do you think we can merge this already? We use it in production since a while.

**Comment by AndreaVitale** [comment]
@hansemannn yes, I'll do it right now if you confirm that you haven't find any issue. 
I tried to update to glide 4.10.0, to avoid all annoying ExifInterface verbose logs, but we can't due to missing androidx support by Titanium.

**Comment by hansemannn** [comment]
Thats coming in a few weeks with SDK 9. I will do some additional tests, but I think it was working fine.

**Comment by AndreaVitale** [comment]
Nice, I was discouraged by the latest comment on [here](https://jira.appcelerator.org/browse/TIMOB-26472)! Let me know :-)

**Comment by hansemannn** [comment]
Basic Gradle support already works, I think the only blocker was Hyperloop (which was already a few weeks ago). Fingers crossed that @jquick-axway solves this :)

**Comment by jquick-axway** [comment]
We plan on having QE test Titanium's gradle PR this week. The team is fast tracking gradle now. If all goes well, it'll be merged by the end of this week. AndroidX support will be added after that PR.

**Comment by hansemannn** [comment]
<3 Thx Josh! That will fix a loooot of our module issues.

**Comment by hansemannn** [comment]
@AndreaVitale Unfortunately it does not work right now:
```
[WARN]  Glide: Load failed for file:///data/user/0/com.company.myapp/cache/my_cache/4e9c10be-c419-1989-f698-c1593a98b4e0.png with size [860x1398]
[WARN]  Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
[WARN]  Glide: There was 1 cause:
[WARN]  Glide: java.lang.ClassCastException(sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection)
[WARN]  Glide:  call GlideException#logRootCauses(String) for more detail
[WARN]  Glide:   Cause (1 of 1): class java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
```
It seems like a casting issue between `FileURLConnection` and `HttpURLConnection`.

**Comment by AndreaVitale** [comment]
@hansemannn the latest commit must solve your issue. I think it is the same one notified by @m1ga :-)

**Comment by prashantsaini1** [comment]
@AndreaVitale  I think the `setImageAsLocalUri()` method is incomplete as it does not use `String filename` argument anywhere and that's why the v4.0.0 is failing to load local-images.

**Comment by m1ga** [comment]
@prashantsaini1 :smile:  https://github.com/AndreaVitale/av.imageview/issues/63#issuecomment-564128586 found the same bug

**Comment by prashantsaini1** [comment]
@m1ga and I just made the exact same code changes 😃  before I could read your comment

**Comment by hansemannn** [comment]
@AndreaVitale @m1ga This is the diff I got from @prashantsaini1 to solve the local images - but I kind of lost track which version should be used now:

Bildschirmfoto 2019-12-10 um 19 44 07

**Comment by hansemannn** [comment]
The following error happens in scrollable views after scrolling a bit between the screens: 
```
[ERROR] TiDrawableReference: (main) [2418,73162] Drawable resource could not be opened. Are you sure you have the resource for the current device configuration (orientation, screen size, etc.)?
[ERROR] InputEventReceiver: Exception dispatching input event.
[ERROR] E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
[ERROR] E/MessageQueue-JNI: android.content.res.Resources$NotFoundException: Resource ID #0x7f0200fd
[ERROR] E/MessageQueue-JNI: 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
[ERROR] E/MessageQueue-JNI: 	at android.content.res.ResourcesImpl.openRawResource(ResourcesImpl.java:352)
[ERROR] E/MessageQueue-JNI: 	at android.content.res.Resources.openRawResource(Resources.java:1301)
[ERROR] E/MessageQueue-JNI: 	at android.content.res.Resources.openRawResource(Resources.java:1245)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.view.TiDrawableReference.getInputStream(TiDrawableReference.java:869)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.view.TiDrawableReference.getBitmap(TiDrawableReference.java:344)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.view.TiDrawableReference.getBitmap(TiDrawableReference.java:328)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.view.TiDrawableReference.getBitmap(TiDrawableReference.java:312)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.view.TiDrawableReference.getDrawable(TiDrawableReference.java:492)
[ERROR] E/MessageQueue-JNI: 	at av.imageview.AvImageView.setImageAsLocalUri(AvImageView.java:195)
[ERROR] E/MessageQueue-JNI: 	at av.imageview.AvImageView.processProperty(AvImageView.java:114)
[ERROR] E/MessageQueue-JNI: 	at av.imageview.AvImageView.processProperties(AvImageView.java:80)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1293)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:508)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:498)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:464)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:515)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:498)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:464)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:515)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:498)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:464)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:515)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:498)
[ERROR] E/MessageQueue-JNI: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:464)
[ERROR] E/MessageQueue-JNI: 	at ti.modules.titanium.ui.widget.TiUIScrollableView$ViewPagerAdapter.instantiateItem(TiUIScrollableView.java:762)
[ERROR] E/MessageQueue-JNI: 	at android.support.v4.view.PagerAdapter.instantiateItem(PagerAdapter.java:114)
[ERROR] E/MessageQueue-JNI: 	at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1004)
[ERROR] E/MessageQueue-JNI: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1218)
[ERROR] E/MessageQueue-JNI: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
[ERROR] E/MessageQueue-JNI: 	at android.support.v4.view.ViewPager$3.run(ViewPager.java:267)
[ERROR] E/MessageQueue-JNI: 	at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:1999)
[ERROR] E/MessageQueue-JNI: 	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2129)
[ERROR] E/MessageQueue-JNI: 	at ti.modules.titanium.ui.widget.TiUIScrollableView$1.onInterceptTouchEvent(TiUIScrollableView.java:108)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2609)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGr
```

**Comment by hansemannn** [comment]
Okay, it happens for local images when used with an AVImageView configured with:
```
	contentMode: Alloy.Globals.CONTENT_MODE_ASPECT_FILL,
	borderRadius: 15
```

**EDIT**: It seems like the changes from @prashantsaini1 are incomplete so far. The issue happens only for local images, e.g. `$.myImage.image = '/images/test.png'` which seems to be unhandled so far.

**Comment by AndreaVitale** [comment]
@hansemannn could you please test the latest android dist inside release folder?

I tested this code and haven't found any issues:

```
setTimeout(() => imageView.image = '/images/bg.jpg', 2000);
setTimeout(() => imageView.image = 'http://www.gstatic.com/webp/gallery/1.webp', 3000);

setTimeout(() => {
    const fileRef = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, '/placeholder.png');

    if (fileRef.exists()) {
        imageView.image = fileRef.nativePath;
    }
}, 4000);
```

**Comment by hansemannn** [comment]
@AndreaVitale First of all, - really - THANK YOU for keep looking into this and maintaining this module. It's a really great addition to the platform and we couldn't live without it. If I can help with any kind of iOS module, always let me know!

--

I tried the latest 4.0.0 build but unfortunately still getting display issues with  local files (and actually all files after that). I see the following in my logs:
```
[ERROR] TiDrawableReference: (main) [102,1514] Drawable resource could not be opened. Are you sure you have the resource for the current device configuration (orientation, screen size, etc.)?
```

May it is related to density specific images again? I will try to get a test case ready.

**Comment by AndreaVitale** [comment]
Yes, a reproducible test case could help!

In my previous sample code, the line 
```setTimeout(() => imageView.image = '/images/bg.jpg', 2000);```
loads a density specific image without issue :-(


Schermata 2019-12-10 alle 23 10 32

**Comment by prashantsaini1** [comment]
@hansemannn @AndreaVitale the changes I did are already handling the local images as per the code suggested by @m1ga as well. The reason I made a check on file:// type urls because drawable was unable to get it, and Glide was just loading the filename directly. I think there's something else fishy going on. Note that we did all testing on Android 10.

**Comment by hansemannn** [comment]
One open issue as described in #63

**Comment by hansemannn** [comment]
I suppose the threading issue is happening somewhere in [this method implementation](https://github.com/AndreaVitale/av.imageview/pull/75/files#diff-d19bd65dceba6ae9a73cb89505e791eaR86-R116).

**Comment by AndreaVitale** [comment]
I made a simple test.

Here is the `index.xml`
```
<Alloy>
	<Window class="container">
		<ScrollableView>
			<Widget src="av.imageview.photo" image="https://dummyimage.com/400x800&text=1"></Widget>
			<Widget src="av.imageview.photo" image="https://dummyimage.com/400x800&text=2"></Widget>
			<Widget src="av.imageview.photo" image="https://dummyimage.com/400x800&text=3"></Widget>
			<Widget src="av.imageview.photo" image="https://dummyimage.com/400x800&text=4"></Widget>
			<Widget src="av.imageview.photo" image="https://dummyimage.com/400x800&text=5"></Widget>
			<ImageView module="av.imageview" image="https://dummyimage.com/400x800&text=6"></ImageView>
			<ImageView module="av.imageview" image="https://dummyimage.com/400x800&text=7"></ImageView>
		</ScrollableView>
	</Window>
</Alloy>
```

and inside `av.imageview.photo` widget.js I have:

```
if ($.args.image) {
    Ti.API.info('Setting image inside widget to', $.args.image);

    $.Photo.image = $.args.image;
}
```

And here is the log:
```
[INFO]  av.imageview-test-alloy 1.0 (Powered by Titanium 8.3.0.2a73828e30)
[DEBUG] NetworkSecurityConfig: No Network Security Config specified, using platform default
[DEBUG] APSAnalyticsService: 1 analytics event(s) queued
[DEBUG] APSAnalyticsService: Attempting to send 1 analytics event(s)
[TRACE] updating tiapp metadata with Appcelerator Platform...
[INFO]  Setting image inside widget to https://dummyimage.com/400x800&text=1
[DEBUG] AvImageView: Setting image url inside 'processProperty' method to https://dummyimage.com/400x800&text=1
[DEBUG] AvImageView: Setting image uri inside 'setImageAsURL' method to https://dummyimage.com/400x800&text=1
[DEBUG] AvImageView: Setting image uri inside 'setImageAsURL' method to https://dummyimage.com/400x800&text=1
[INFO]  Setting image inside widget to https://dummyimage.com/400x800&text=2
[DEBUG] AvImageView: Setting image url inside 'processProperty' method to https://dummyimage.com/400x800&text=2
[DEBUG] AvImageView: Setting image uri inside 'setImageAsURL' method to https://dummyimage.com/400x800&text=2
[DEBUG] AvImageView: Setting image uri inside 'setImageAsURL' method to https://dummyimage.com/400x800&text=2
[INFO]  Setting image inside widget to https://dummyimage.com/400x800&text=3
[DEBUG] AvImageView: Setting image url inside 'processProperty' method to https://dummyimage.com/400x800&text=3
[DEBUG] AvImageView: Setting image uri inside 'setImageAsURL' method to https://dummyimage.com/400x800&text=3
[DEBUG] AvImageView: Setting image uri inside 'setImageAsURL' method to https://dummyimage.com/400x800&text=3
[INFO]  Setting image inside widget to https://dummyimage.com/400x800&text=4
[DEBUG] AvImageView: Setting image url inside 'processProperty' method to https://dummyimage.com/400x800&text=4
[DEBUG] AvImageView: Setting image uri inside 'setImageAsURL' method to https://dummyimage.com/400x800&text=4
[DEBUG] AvImageView: Setting image uri inside 'setImageAsURL' method to https://dummyimage.com/400x800&text=4
[INFO]  Setting image inside widget to https://dummyimage.com/400x800&text=5
[DEBUG] AvImageView: Setting image url inside 'processProperty' method to https://dummyimage.com/400x800&text=5
[DEBUG] AvImageView: Setting image uri inside 'setImageAsURL' method to https://dummyimage.com/400x800&text=5
[DEBUG] AvImageView: Setting image uri inside 'setImageAsURL' method to https://dummyimage.com/400x800&text=5
```

as you can see the `cacheSize` seems to work differently between widgets and proxies.
`cacheSize` by default is `3` so, what I'm expecting is that images 1, 2 and 3 must be loaded immediately, image 4 must be loaded when the `ScrollableView` scrolls to index `1` and so on.
In fact proxies with images 6 and 7 aren't created until I scroll to `ScrollableView` index 4 and 5 respectively.

At this point.. I raise an hand and I ask help! Do you have any idea on how to handle that without playing with `ScrollableView.scroll` event?

**Comment by prashantsaini1** [comment]
AFAIK, cacheSize 3 means there'll be only 3 views in memory at a time. One which is visible and two on left/right.

**Comment by AndreaVitale** [comment]
@prashantsaini1 exactly, look at this: https://github.com/appcelerator/titanium_mobile/blob/c4a01b3438696c37902a9f6252e0842b177b13b0/android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollableView.java#L448

**Comment by m1ga** [comment]
@AndreaVitale I was doing a lot of debugging tests with the widgets too but couldn't find a solution for it. There was an old bug for version 2.x https://github.com/AndreaVitale/av.imageview/issues/26 that was fixed with automatic getters/setters through `propertyAccessors`. Perhaps there is something wrong with the custom setter and the missing getter? E.g. the current `setImage()` is using `this.setProperty("image", uri.toString());` will make it set the image twice because it will set the property and that will call propertyChanged (which calls `setImageAsURL`) and after that it will call `setImageAsURL` with the url. But I've remove one and it still didn't work with the widgets.

**Comment by hansemannn** [comment]
I still haven't found the issue as well. Here are my top 3 ideas what could cause it:
- Access to "image" setter from background thread / general thread handling
- URL sanitize does not happen any more as far as I can see (used a "sanitize()" proxy utility method before)
- Global scope issue in Alloy causing issues in widgets. I looked into some generated controllers but they look normal.

This is an absolute blocker.

**Comment by hansemannn** [comment]
@AndreaVitale It works very well now - in all cases we have:

- Local images
- Remote images
- Blobs
- Caching
- Widget support
- Parity with iOS

I hear a merge train arriving! 🚂

**Comment by AndreaVitale** [comment]
PR was merged. Thank you all guys for your support and feedback!

**Pull request merged**
