### PR TITLE
feat: support iOS 14 by using SDWebImage 5.8.4

### LINKED ISSUE #90: Support iOS 14
It seems like images are currently not displayed when running on iOS 14.

### PR DESCRIPTION
**Pull request by hansemannn**
Fixes #90

### CODE REVIEW

**Comment by hansemannn** [comment]
@AndreaVitale would you check this out? ✌️

**Comment by AndreaVitale** [comment]
So it wasn't a module bug but the iOS 14 supports comes directly from SDWebImage?
I'm pulling your PR to have a check!

**Comment by AndreaVitale** [comment]
PR approved! Thank you @hansemannn !

**Comment by hansemannn** [comment]
@AndreaVitale Yep, it was an issue in the layer processing and was officially announced as a "iOS 14 fix" from SDWebImage. Everything works fine again now!

**Comment by AndreaVitale** [comment]
Hi @hansemannn have you encountered lags using the newest version of the module?
I have an app I'm building that with the previous version (including SDWebImage 5.8.0) works fine and smoothly. 
With the new one I have tremendous lags and also seems that it doesn't handle correctly the brokenLinkImage property.

Here are the screencasts:
- [with SDWebImage 5.8.0](https://drive.google.com/file/d/1l_ELBTPvSYXiUxYTUbGCRpD3IIUqqKoy/view?usp=sharing) (old module version)
- [with SDWebImage 5.8.4](https://drive.google.com/file/d/125omEliTK4SCeN64t-SzE5045Ga_uCJS/view?usp=sharing)

**Comment by hansemannn** [comment]
Mhhhh, interesting. Maybe they changed something threading related? In that case, we should take a closer look into their changelog.

**Pull request merged**
