### PR TITLE
able to set timeout for image requests

### LINKED ISSUE #34: setTimeout for Glide
Hi @AndreaVitale how can we set a timeout for request when loading an image?

### PR DESCRIPTION
**Pull request by bduyng**

### CODE REVIEW

**Comment by bduyng** [comment]
resolve #34

**Comment by AndreaVitale** [comment]
Hi @bduyng thanks for your contribution! Could you please update the README? Could you also provide a solution also for iOS? Thank you!

**Comment by bduyng** [comment]
@AndreaVitale you are welcome! I will update the README and will have a look iOS as soon as possible!!

**Comment by AndreaVitale** [comment]
That is so much appreciated. When the PR finished with the iOS updated version I will merge it for sure

**Comment by bduyng** [comment]
hi @AndreaVitale please check ☝️

**Comment by AndreaVitale** [comment]
Meeeeeerged! Thank you 🥇

**Comment by bduyng** [comment]
wow, that is fast! Thanks, Andrea! 🍻

**Comment by bduyng** [comment]
@AndreaVitale can you please update release builds as well?

**Comment by AndreaVitale** [comment]
@bduyng is in progress :-) Thank you

**Pull request merged**
