### PR TITLE
Android: SDK 9 update

### PR DESCRIPTION
**Pull request by m1ga**
[av.imageview-android-4.1.0.zip](https://github.com/AndreaVitale/av.imageview/files/4580512/av.imageview-android-4.1.0.zip)

* glide 4.11.0
* ti sdk 9+
* some code clean-up

### CODE REVIEW

**Comment by hansemannn** [comment]
+1 for this. Maybe merge already and do the Glide update separately?

**Comment by m1ga** [comment]
its already using the latest now and was working fine in my tests. Need to update the first post :)

**Comment by m1ga** [comment]
@AndreaVitale you can have a look now!

**Comment by hansemannn** [comment]
Same here! Just tried the 4.11.0 locally and it works fine.

**Comment by AndreaVitale** [comment]
Thanks @m1ga ! I'll have a look today.

**Comment by ffMathy** [comment]
@AndreaVitale any news on this?

**Comment by AndreaVitale** [comment]
The issue #81 is verified also with your version @m1ga :(

**Comment by hansemannn** [comment]
@AndreaVitale This PR does not include other changes than updating to Gradle and a few code style changes.

**Comment by m1ga** [comment]
@AndreaVitale fixed the 1st one (applying the values one at a time). Just the `propertyChanged` is in the wrong order when using
```
$.image2.applyProperties({
		brokenLinkImage: "/images/appicon.png",
		defaultImage: "/images/appicon.png",
		image: "https://this.is.a.broken.link.com/image.png"
	});;
```
is setting the image first and after that the default/broken image.

**Comment by AndreaVitale** [comment]
Thank you for your work @m1ga , merged!

**Pull request merged**
