### PR TITLE
New validatesSecureCertificate to bypass SSL validation

### PR DESCRIPTION
**Pull request by phobeous**

### CODE REVIEW

**Comment by AndreaVitale** [comment]
Hi @phobeous thank you for your PR!
To avoid that the `AVImageView.java` grows enormously, could you move all clients, certs and context factories in a separate files under `utils` folder like we do with `CookiesHelper.java` and `ImageLoader.java`?

**Comment by phobeous** [comment]
Sure @AndreaVitale ! I'll do ASAP

**Comment by phobeous** [comment]
@AndreaVitale done. What do you think about? Is it ok?

**Comment by AndreaVitale** [comment]
Great @phobeous, it's perfect, Thank you!!

**Pull request merged**
