### PR TITLE
ti 7 compatibility

### PR DESCRIPTION
**Pull request by m1ga**
update: zip included in the PR

### CODE REVIEW

**Comment by AndreaVitale** [comment]
Hi @m1ga thanks for your PR! Is this finished? A module compiled for Ti SDK 7.x is fully compatible with an app built with Ti SDK 6?

**Comment by m1ga** [comment]
No, it will only work 7+ you'll have to keep the old binary version for SDK 6 

And yes, its finished. Its only a recompile of the current version with a new manifest. No code changes

**Comment by yankovalera** [comment]
Hi @m1ga 

I've tried to use your built module and got this error...

[ERROR] TiApplication: (main) [13,1215] Sending event: exception on thread: main msg:java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.app.id-4TMClH6dV4K_3RscY8-Riw==/base.apk"],nativeLibraryDirectories=[/data/app/com.app.id-4TMClH6dV4K_3RscY8-Riw==/lib/arm64, /data/app/com.app.id-4TMClH6dV4K_3RscY8-Riw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libav.imageview.so"; Titanium 7.0.0,2017/12/05 13:30,undefined
[ERROR] TiApplication: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.app.id-4TMClH6dV4K_3RscY8-Riw==/base.apk"],nativeLibraryDirectories=[/data/app/com.app.id-4TMClH6dV4K_3RscY8-Riw==/lib/arm64, /data/app/com.app.id-4TMClH6dV4K_3RscY8-Riw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libav.imageview.so"
[ERROR] TiApplication: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
[ERROR] TiApplication: 	at java.lang.System.loadLibrary(System.java:1657)
[ERROR] TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
[ERROR] TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
[ERROR] TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
[ERROR] TiApplication: 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
[ERROR] TiApplication: 	at com.app.id.AApplication.onCreate(AApplication.java:55)
[ERROR] TiApplication: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
[ERROR] TiApplication: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
[ERROR] TiApplication: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
[ERROR] TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
[ERROR] TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:105)
[ERROR] TiApplication: 	at android.os.Looper.loop(Looper.java:164)
[ERROR] TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
[ERROR] TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiApplication: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Any idea what might be happening?

Regards

**Comment by m1ga** [comment]
try cleaning your build folder and (if its not already there) create the libs/arm64-v8a folder. Sometimes it get stuck there.

Edit:
compiling the module or using it in an app?

**Comment by m1ga** [comment]
My fault! The ZIP in the PR war correct. I've just uploaded an old one to my webspace! File is correct now. The `libs/arm64-v8a` was missing in my zip

**Comment by yahya-uddin** [comment]
+1

**Comment by AndreaVitale** [comment]
Merged! Thank you @m1ga !!

**Comment by kerberosargos** [comment]
@m1ga  @AndreaVitale  I am getting same error with Android 3.1.0 . Thank you for your effort. Error as below;

`TiApplication: (main) [51,3881] Sending event: exception on thread: main msg:java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sizebiz.reading-2/base.apk"],nativeLibraryDirectories=[/data/app/com.sizebiz.reading-2/lib/arm, /data/app/com.sizebiz.reading-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libav.imageview.so"; Titanium 7.0.1,2017/12/18 10:42,undefined
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sizebiz.reading-2/base.apk"],nativeLibraryDirectories=[/data/app/com.sizebiz.reading-2/lib/arm, /data/app/com.sizebiz.reading-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libav.imageview.so"`

**Pull request merged**
