### PR TITLE
Android: Move to proper directory structure, add dontAnimate/setSignature/setImage(null)

### PR DESCRIPTION
**Pull request by m1ga**
Sorry for the big PR! The directory structure was mixed up and I've corrected it (there was an additional /android folder). 

* Moved all files from /android/android to /android
* Add `dontAnimate` property that disables the fade-in for normal (local) images `dontAnimate()` before `into()`
* Applied clang to the main JAVA files
* version 3.3.0
* `setImage(null)` to remove the image
* `setSignature()` to set add a caching signature to the loader
* updated okhttp + okio (from https://github.com/AndreaVitale/av.imageview/pull/59)

No rewrite to 4 :smile: 

**Example**
```
$.index.open();

function onClick1(e) {
	console.log("old", $.image.dontAnimate);
	$.image.setDontAnimate(true);
	$.image.setImage("/appicon.png");
	console.log("new", $.image.getDontAnimate());
}

function onClick2(e) {
	console.log("old", $.image.getDontAnimate());
	$.image.dontAnimate = false;
	$.image.setImage("/appicon.png");
	console.log("new", $.image.dontAnimate);
}
function onClick3(e) {
	$.image.setImage(null);
}
```

```xml
<Alloy>
	<Window class="container">
		<ImageView id="image" module="av.imageview"/>
		<Button id="btn1" title="1" onClick="onClick1"/>
		<Button id="btn2" title="2" onClick="onClick2"/>
		<Button id="btn3" title="clear" onClick="onClick3"/>
	</Window>
</Alloy>
```

```
".container" : {
	backgroundColor: "white"
}
"#image" : {
	width: 200,
	height: 200,
	image: "/appicon.png"
}
"#btn1" : {
	bottom: 0
}
"#btn2" : {
	bottom: 40
}
"#btn3" : {
	bottom: 80
}

```

Binary: https://migaweb.de/av.imageview-android-3.3.0.zip

### CODE REVIEW

**Comment by m1ga** [comment]
added a proper gitignore to remove the android build folder and added an example! Ready to merge :)

**Comment by AndreaVitale** [comment]
Hi @m1ga ! Thank you for your work! Once there will be a parity with iOS I'll merge it for sure. At the moment I'm really busy but I will do it when I have a bit of time (hoping soon). I'll let you know!

**Comment by m1ga** [comment]
I've added `setSignature()` that allows to add a custum string to the cache mechanism (https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation). I had problems changing images and the old image appeared again from time to time. Reading the documentation it looks like adding a custom signature will get rid of that (and in my current tests it looks like it is working :smile: )

**Comment by hansemannn** [comment]
Would love to see this in!

**Comment by AndreaVitale** [comment]
Great work @m1ga really really thank you!

**Comment by m1ga** [comment]
the binary is here: https://migaweb.de/av.imageview-android-3.3.0.zip in case you don't want to build it on your own

**Pull request merged**
